version: 2
updates:
  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  # node packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    groups:
      prisma:
        patterns:
          - "prisma"
          - "@prisma/client"
          - "@prisma/adapter-pg"
      patch:
        update-types:
          - "patch"
