name: setup node and dependencies
description: setups up node, dependencies, file structure and prisma

runs:
  using: composite

  steps:
    - name: install pnpm
      uses: pnpm/action-setup@v6
      with:
        version: 11

    - name: use node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: "pnpm"

    - name: enable node-gyp tooling
      shell: bash
      run: npm install -g node-gyp

    - name: install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: run setup.sh
      shell: bash
      run: bash setup.sh

    - name: setup prisma
      shell: bash
      run: npx prisma generate
