name: cd

on:
  push:
    tags:
      - "*"
jobs:
  deploy:
    concurrency: deploy

    runs-on: ubuntu-latest

    steps:
      - name: connect to server & pull changes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          password: ${{ secrets.PASS }}
          script: |
            cd ~/nypsi
            git pull
            git status
            npm i
            npx tsc
