name: formatting

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: ./.github/actions/setup

      - name: check formatting
        run: pnpm run format:check
