name: Prettier
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
            - uses: actions/checkout@v2
            - name: setup node
            - uses: actions/setup-node@v2

            - name: npm install
            - run: npm install

            - name: formatting
            - run: npm run format

            - name: publish to github
            - run: git status
            # commit any changed files
            # https://github.com/mikeal/publish-to-github-action
            - uses: tekoh/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH_NAME: ${GITHUB_REF##*/}
