name: formatting

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for manually triggering this workflow"
        required: false
  schedule:
    - cron: "0 0 * * *"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout repo
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        name: setup node
        with:
          node-version: 18

      - uses: pnpm/action-setup@v4
        name: install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: format
        run: npm run format

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: formatting"
          branch: ${{ github.head_ref }}
