name: Prettier
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v2

            - name: install packages
              run: npm install

            - name: formatting
              run: npm run format

            - name: publish to github
                - run: git status
                - uses: tekoh/publish-to-github-action@master
                    env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    BRANCH_NAME: ${GITHUB_REF##*/}
