name: Prettier
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v2
              
            - name: setup node
              uses: actions/setup-node@v2

            - name: install packages
              run: npm install

            - name: getting branch name
              id: branch-name
              uses: tj-actions/branch-names@v5.1

            - name: fetch
              run: git fetch
            - name: checkout
              run: git branch

            - name: formatting
              run: npm run format

            - name: git status
              run: git status

            - name: publish to github
              uses: tekoh/publish-to-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH_NAME: ${{ steps.branch-name.outputs.current_branch }}
