name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    name: Linting
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
  
      - run: npx eslint ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5
      
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: node nypsi.js